apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: leveldb-pvc
  namespace: leveldb-nodeapp-poc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: hostpath

  resources:
    requests:
      storage: 5Gi